name: Docker Image Deployement to Azure Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DOCKER_IMAGE_NAME: 'arojayathilaka/memory-stash'
  DOCKER_FILE_PATH: './memory-stash'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./memory-stash/Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}'
