name: Docker Image Deployement to Azure Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DOCKER_IMAGE_NAME: 'arojayathilaka/memory-stash'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}'

    - name: Docker Login
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}' '${{env.DOCKER_IMAGE_NAME}}'
    - name: Push the Docker image
      run: docker push '${{env.DOCKER_IMAGE_NAME}}'
